### ISSUE TITLE
Deploy API and expose seed data on plant details

### ISSUE THREAD

**Issue by Daveroen** [BCIT-SSD-2020-21/indigenous-plant-go-cms#67]
- Created initial set-up cluster for mongo atlas
- Set-up deployment configuration for heroku
- Linked fixiesocks for ip address/heroku
- AWS S3 set-up

**Comment by Wayl123** [comment]
I think this can be considered completed but there may be some stuff that may be worth looking over like having an specific ip for mongodb atlas to connect to etc.
